"""empty message

Revision ID: d740885cdfda
Revises: d6191c4dc833
Create Date: 2021-04-08 01:28:47.638674

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd740885cdfda'
down_revision = 'd6191c4dc833'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('planets_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'character', 'planets', ['planets_id'], ['id'])
    op.add_column('favorites', sa.Column('favorite_id', sa.Integer(), nullable=False))
    op.drop_column('favorites', 'object_id')
    op.drop_column('planets', 'imgPlanet')
    op.drop_column('user', 'name')
    op.drop_column('user', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_name', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('user', sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('planets', sa.Column('imgPlanet', mysql.VARCHAR(length=300), nullable=True))
    op.add_column('favorites', sa.Column('object_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('favorites', 'favorite_id')
    op.drop_constraint(None, 'character', type_='foreignkey')
    op.drop_column('character', 'planets_id')
    # ### end Alembic commands ###
